### SIGNUP USER
POST http://localhost:8000/api/auth/signup
content-type: application/json

{
  "firstName": "Lars-Åke",
  "lastName": "Andersson",
  "email": "gunnar@bertilsson.se"
}

### LOGIN USER
POST http://localhost:8000/api/auth/login
content-type: application/json

{
  "email": "gunnar@bertilsson.se",
  "password": "test1234"
}

### 
POST http://localhost:8000/api/playlist/6141ebe63239244c6adbbeab/kaOOfci2YC8
content-type: application/json

{
  "type": "song",
  "videoId": "kaOOfci2YC8",
  "playlistId": "RDAMVMkaOOfci2YC8",
  "name": "Nothing Else Matters",
  "artist": {
    "name": "Metallica",
    "browseId": "UCGexNm_Kw4rdQjLxmpb2EKw"
    }
}